# Generated by Django 5.2 on 2025-06-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_alter_pedido_estado_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en camino', 'En camino'), ('enviado', 'Enviado'), ('entregados', 'Entregados')], max_length=20),
        ),
    ]
