# Generated by Django 5.2 on 2025-06-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en camino', 'En camino'), ('entregados', 'Entregados')], max_length=20),
        ),
    ]
